AnimeLibrary/Models/AnimeViewModel.cs
namespace AnimeLibrary.Models
{
    public class AnimeViewModel
    {
        public int Id { get; set; }
        public string? RomajiTitle { get; set; }
        public string? EnglishTitle { get; set; }
        public string? NativeTitle { get; set; }
        public string? CoverImage { get; set; }
        public string? Description { get; set; }
        public List<string>? Genres { get; set; }
        public double? Score { get; set; }
        public DateTime? StartDate { get; set; }
        public int? Episodes { get; set; }
        public string? Trailer { get; set; }
        public double? AverageScore { get; set; }
        public string RelationType { get; set; }
        public string? Genre { get; set; }
        public List<Media> Animes { get; set; }
        public List<RelatedAnimeViewModel> RelatedAnime { get; set; }
        public List<CharacterViewModel> Characters { get; set; }

        public class RelatedAnimeViewModel
        {
            public int Id { get; set; }
            public string Title { get; set; }
            public string CoverImage { get; set; }
            public string RelationType { get; set; }
            public string Type { get; set; }
        }

    }
    public class AnimeGenreViewModel
    {
        public string Genre { get; set; }
        public List<AnimeViewModel> Animes { get; set; }
        public List<string> Genres { get; set; }
    }


    public class HomeViewModel
    {
        public List<AnimeViewModel> CurrentlyAiring { get; set; }
        public List<AnimeViewModel> CurrentSeason { get; set; }
        public List<AnimeViewModel> Action { get; set; }
        public List<AnimeViewModel> Romance { get; set; }
        public List<AnimeViewModel> Comedy { get; set; }
        public List<AnimeViewModel> Music { get; set; }
        public List<AnimeViewModel> Drama { get; set; }
        public List<AnimeViewModel> Horror { get; set; }
        public List<AnimeViewModel> Sports { get; set; }
        public List<AnimeViewModel> Psychological { get; set; }
        public List<AnimeViewModel> Fantasy { get; set; }
        public List<AnimeViewModel> Ecchi { get; set; }
        public List<string>? Genres { get; set; }
        public string? Genre {  get; set; }
        public List<int>? Years { get; set; }
        public List<AnimeViewModel>? AllAnimes { get; set; }
        public List<MangaViewModel>? AllMangas { get; set; }

        public IEnumerable<News> News { get; set; }

    }
}

AnimeLibrary/Controllers/AnimeController.cs
using AnimeLibrary.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Threading.Tasks;

namespace AnimeLibrary.Controllers
{
    public class AnimeController : Controller
    {
        private readonly AniListService _aniListService;
        private readonly UserManager<ApplicationUser> _userManager;

        public AnimeController(AniListService aniListService, UserManager<ApplicationUser> userManager)
        {
            _aniListService = aniListService;
            _userManager = userManager;
        }
        [ResponseCache(Duration = 60)]
        public async Task<IActionResult> Details(int id)
        {
            var anime = await _aniListService.GetAnimeDetails(id);
            if (anime == null)
            {
                return NotFound();
            }
            var relatedAnime = await _aniListService.GetRelatedAnimeAsync(id);
            var viewModel = new AnimeViewModel
            {
                Id = anime.Id,
                RomajiTitle = anime.RomajiTitle,
                EnglishTitle = anime.EnglishTitle,
                NativeTitle = anime.NativeTitle,
                CoverImage = anime.CoverImage,
                Description = anime.Description,
                Genres = anime.Genres,
                Score = anime.Score,
                StartDate = anime.StartDate,
                Episodes = anime.Episodes,
                RelatedAnime = relatedAnime,
                Characters = anime.Characters,
                Trailer = anime.Trailer,
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Genre(string genre, int page = 1, int perPage = 15)
        {
            // Асинхронно получаем список аниме по жанру и странице
            var animeListByGenre = await _aniListService.ListAnimeGenre(genre, page, perPage);
            if (animeListByGenre == null || !animeListByGenre.Any())
            {
                return NotFound();
            }

            // Преобразуем список Media в список AnimeViewModel
            var animeViewModels = animeListByGenre.Select(media => new AnimeViewModel
            {
                Id = media.Id,
                RomajiTitle = media.Title.Romaji,
                EnglishTitle = media.Title.English,
                NativeTitle = media.Title.Native,
                CoverImage = media.CoverImage.Large,
                Description = media.Description,
                Genres = media.Genres,
                Genre = genre,
                Score = media.Score,
                Episodes = media.Episodes,
                AverageScore = media.AverageScore,
            }).ToList();

            var allGenres = await _aniListService.GetGenresAsync();

            var viewModel = new AnimeGenreViewModel
            {
                Genre = genre,
                Animes = animeViewModels,
                Genres = allGenres ?? new List<string>()
            };

            return View("Genre", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToViewed(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var anime = await _aniListService.GetAnimeDetails(id);
            if (anime == null)
            {
                return NotFound();
            }

            if (user.ViewedAnimes == null)
            {
                user.ViewedAnimes = new List<int>();
            }

            if (!user.ViewedAnimes.Contains(anime.Id))
            {
                user.ViewedAnimes.Add(anime.Id);
                await _userManager.UpdateAsync(user);
            }

            return RedirectToAction("ViewedContent", "Account");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveFromViewed(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (user.ViewedAnimes == null || !user.ViewedAnimes.Contains(id))
            {
                return NotFound();
            }

            user.ViewedAnimes.Remove(id);
            await _userManager.UpdateAsync(user);

            return RedirectToAction("ViewedContent", "Account");
        }

        public async Task<IActionResult> Search(string title)
        {
            if (string.IsNullOrWhiteSpace(title))
            {
                return PartialView("_SearchResults", new List<AnimeViewModel>());
            }

            try
            {
                var searchResults = await _aniListService.SearchAnimeByTitleAsync(title);
                var animeList = searchResults["Page"]["media"].ToObject<List<Media>>();

                var animeViewModels = animeList.Select(media => new AnimeViewModel
                {
                    Id = media.Id,
                    RomajiTitle = media.Title?.Romaji,
                    EnglishTitle = media.Title?.English,
                    NativeTitle = media.Title?.Native,
                    CoverImage = media.CoverImage?.Large,
                    Description = media.Description,
                    Genres = media.Genres,
                    Score = media.Score.HasValue ? media.Score.Value / 10.0 : (double?)null,
                    Episodes = media.Episodes,
                    AverageScore = media.AverageScore,
                }).ToList();

                return PartialView("_SearchResults", animeViewModels);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return PartialView("_SearchResults", new List<AnimeViewModel>());
            }
        }

        public async Task<IActionResult> LoadMoreAnime(string genre, int page = 1, int perPage = 15)
        {
            var animeListByGenre = await _aniListService.ListAnimeGenre(genre, page, perPage);
            if (animeListByGenre == null || !animeListByGenre.Any())
            {
                return NotFound();
            }

            var animeViewModels = animeListByGenre.Select(media => new AnimeViewModel
            {
                Id = media.Id,
                RomajiTitle = media.Title.Romaji,
                EnglishTitle = media.Title.English,
                NativeTitle = media.Title.Native,
                CoverImage = media.CoverImage.Large,
                Description = media.Description,
                Genres = media.Genres,
                Genre = genre,
                Score = media.Score,
                Episodes = media.Episodes,
                AverageScore = media.AverageScore,
            }).ToList();

            return PartialView("_AnimeListPartial", animeViewModels);
        }




    }

}

AnimeLibrary/Controllers/CharacterController.cs
using AnimeLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AnimeLibrary.Controllers
{
    public class CharacterController : Controller
    {
        private readonly AniListService _aniListService;

        public CharacterController(AniListService aniListService)
        {
            _aniListService = aniListService;
        }
        [ResponseCache(Duration = 60)]
        public async Task<IActionResult> Details(int id)
        {
            // Получаем основные данные персонажа
            var character = await _aniListService.GetCharacterDetailsAsync(id);
            if (character == null)
            {
                return NotFound();
            }

            // Получаем список медиа, где персонаж появляется
            var mediaAppearances = await _aniListService.GetCharacterAppearancesAsync(id);
            character.MediaAppearances = mediaAppearances;

            return View(character);
        }
    }
}

AnimeLibrary/Controllers/MangaController.cs
using AnimeLibrary.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using static AnimeLibrary.Models.TestModel;

public class MangaController : Controller
{
    private readonly AniListService _aniListService;
    private readonly UserManager<ApplicationUser> _userManager;


    public MangaController(AniListService aniListService, UserManager<ApplicationUser> userManager)
    {
        _aniListService = aniListService;
        _userManager = userManager;
    }
    [ResponseCache(Duration = 60)]
    public async Task<IActionResult> Index()
    {
        var trendingManga = await _aniListService.GetTrendingMangaAsync();
        var popularManga = await _aniListService.GetPopularMangaAsync();
        var popularManhwa = await _aniListService.GetPopularManhwaAsync();
        var genres = await _aniListService.GetGenresAsync();
        var viewModel = new MangaViewModel
        {
            TrendingManga = trendingManga ?? new List<MangaViewModel>(),
            PopularManga = popularManga ?? new List<MangaViewModel>(),
            PopularManhwa = popularManhwa ?? new List<MangaViewModel>(),
            Genres = genres
            
        };

        return View(viewModel);
    }
    public async Task<IActionResult> Details(int id)
    {
        // Асинхронно получаем данные об аниме
        var manga = await _aniListService.GetMangaDetails(id);
        if (manga == null)
        {
            return NotFound();
        }
        var relatedManga = await _aniListService.GetRelatedMangaAsync(id);
        var viewModel = new MangaViewModel
        {
            Id = manga.Id,
            TitleRomaji = manga.TitleRomaji,
            TitleEnglish = manga.TitleEnglish,
            TitleNative = manga.TitleNative,
            Description = manga.Description,
            Chapters = manga.Chapters,
            Volumes = manga.Volumes,
            Score = manga.Score,
            CoverImage = manga.CoverImage,
            StartDate = manga.StartDate,
            Genres = manga.Genres,
            RelatedManga = relatedManga
        };

        return View(viewModel);
    }
    public async Task<IActionResult> Genre(string genre, int page = 1, int perPage = 15)
    {
        // Асинхронно получаем список манги по жанру
        var mangaListByGenre = await _aniListService.ListMangaGenre(genre, page, perPage);
        if (mangaListByGenre == null || !mangaListByGenre.Any())
        {
            return NotFound();
        }

        var mangaViewModels = mangaListByGenre.Select(media => new MangaViewModel
        {
            Id = media.Id,
            TitleRomaji = media.Title.Romaji,
            TitleEnglish = media.Title.English,
            TitleNative = media.Title.Native,
            CoverImage = media.CoverImage.Large,
            Description = media.Description,
            Genres = media.Genres,
            Score = media.Score,
            Genre = genre,
            Chapters = media.Chapters,
            AverageScore = media.AverageScore
        }).ToList();

        var allGenres = await _aniListService.GetGenresAsync();

        var viewModel = new MangaGenreViewModel
        {
            Genre = genre,
            Mangas = mangaViewModels,
            Genres = allGenres ?? new List<string>()
        };

        return View("Genre", viewModel);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddToViewed(int id)
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return RedirectToAction("Login", "Account");
        }

        var manga = await _aniListService.GetMangaDetails(id);
        if (manga == null)
        {
            return NotFound();
        }

        if (user.ViewedMangas == null)
        {
            user.ViewedMangas = new List<int>();
        }

        if (!user.ViewedMangas.Contains(manga.Id))
        {
            user.ViewedMangas.Add(manga.Id);
            await _userManager.UpdateAsync(user);
        }

        return RedirectToAction("ViewedContent", "Account");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RemoveFromViewed(int id)
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return RedirectToAction("Login", "Account");
        }

        if (user.ViewedMangas == null || !user.ViewedMangas.Contains(id))
        {
            return NotFound();
        }

        user.ViewedMangas.Remove(id);
        await _userManager.UpdateAsync(user);

        return RedirectToAction("ViewedContent", "Account");
    }
    public async Task<IActionResult> Search(string title)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            return PartialView("_SearchResults", new List<MangaViewModel>());
        }

        try
        {
            var searchResults = await _aniListService.SearchMangaByTitleAsync(title);
            var mangaList = searchResults["Page"]["media"].ToObject<List<Media>>();

            var mangaViewModels = mangaList.Select(media => new MangaViewModel
            {
                Id = media.Id,
                TitleRomaji = media.Title?.Romaji,
                TitleEnglish = media.Title?.English,
                TitleNative = media.Title?.Native,
                CoverImage = media.CoverImage?.Large,
                Description = media.Description,
                Genres = media.Genres,
                Score = media.Score.HasValue ? media.Score.Value / 10.0 : (double?)null,
                AverageScore = media.AverageScore,
            }).ToList();

            return PartialView("_SearchResults", mangaViewModels);
        }
        catch (Exception ex)
        {
            ViewBag.ErrorMessage = ex.Message;
            return PartialView("_SearchResults", new List<MangaViewModel>());
        }
    }
    public async Task<IActionResult> LoadMoreManga(string genre, int page = 1, int perPage = 15)
    {
        // Асинхронно получаем список аниме по жанру и странице
        var mangaListByGenre = await _aniListService.ListMangaGenre(genre, page, perPage);
        if (mangaListByGenre == null || !mangaListByGenre.Any())
        {
            return NotFound();
        }

        var mangaViewModels = mangaListByGenre.Select(media => new MangaViewModel
        {
            Id = media.Id,
            TitleRomaji = media.Title.Romaji,
            TitleEnglish = media.Title.English,
            TitleNative = media.Title.Native,
            CoverImage = media.CoverImage.Large,
            Description = media.Description,
            Genres = media.Genres,
            Genre = genre,
            Score = media.Score,
            Chapters = media.Chapters,
            AverageScore = media.AverageScore,
        }).ToList();

        return PartialView("_MangaListPartial", mangaViewModels);
    }

}

AnimeLibrary/Views/Anime/Details.cshtml
@model AnimeLibrary.Models.AnimeViewModel

@{
    ViewData["Title"] = Model.RomajiTitle;
    var trailerEmbedUrl = !string.IsNullOrEmpty(Model.Trailer) ? $"https://www.youtube.com/embed/{Model.Trailer}" : null;
    var watchEmbedUrl = $"https://www.miruro.tv/watch?id={Model.Id}&ep=1";
}

<div class="anime-details">
    <div class="anime-header">
        <img src="@Model.CoverImage" alt="@Model.EnglishTitle" class="anime-image" />
        <div class="anime-info">
            <h1>@Model.RomajiTitle</h1>
            <h5>@Model.EnglishTitle</h5>
            <h5>@Model.NativeTitle</h5>
            <div id="description" class="description">
                <p>@Html.Raw(Model.Description)</p>
            </div>
            <button id="toggleButton">Подробнее...</button>
        </div>
    </div>
    
    @if (Model.Genres != null && Model.Genres.Any())
    {
        <div class="genres-section">
            <h3>Жанры</h3>
            <ul class="genres-list">
                @foreach (var genre in Model.Genres)
                {
                    <li class="genre-item">@genre</li>
                }
            </ul>
        </div>
    }
    <form asp-action="AddToViewed" method="post">
        <input type="hidden" name="id" value="@Model.Id" />
        <button type="submit" class="btn btn-primary">Добавить в просмотренное</button>
    </form>
    <div class="statistics-section">
        <h3>Статистика</h3>
        <p>Оценка: @(Model.Score.HasValue ? Model.Score.Value.ToString("0.0") : "Rating is unknown.")</p>
        <p>Эпизоды: @(Model.Episodes.HasValue ? Model.Episodes.Value.ToString() : "1000+")</p>
        <p>Дата выхода: @(Model.StartDate.HasValue ? Model.StartDate.Value.ToString("dd.MM.yyyy") : "Release date is unknown.")</p>
    </div>

    @if (Model.RelatedAnime != null && Model.RelatedAnime.Any())
    {
        <div class="related-anime-section">
            <h3>Связанное</h3>
            <div class="related-anime-list">
                @foreach (var related in Model.RelatedAnime)
                {
                    <div class="related-anime-item">
                        @if (@related.Type == "ANIME")
                        {
                            <a class="related-link" href="@Url.Action("Details", "Anime", new { id = related.Id })">
                             <img src="@related.CoverImage" alt="Image @related.Title" />
                             <p class="media-title">@related.Title</p>
                             <p class="media-type">@related.Type</p>
                             </a>
                        } else {
                             <a class="related-link" href="@Url.Action("Details", "Manga", new { id = related.Id })">
                             <img src="@related.CoverImage" alt="Image @related.Title" />
                                <p class="media-title">@related.Title</p>
                                <p class="media-type">@related.Type</p>
                             </a>
                        }
                    </div>
                }
            </div>
        </div>
    }

    @if (!string.IsNullOrEmpty(trailerEmbedUrl))
    {
        <div class="trailer-section">
            <h3>Трейлер</h3>
            <div class="trailer-video">
                <iframe width="560" height="315" src="@trailerEmbedUrl" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    }

    @if (Model.Characters != null && Model.Characters.Any())
    {
        <div class="characters-section">
            <h3>Персонажи</h3>
            <div class="characters-list">
                @foreach (var character in Model.Characters)
                {
                    <div class="character-item">
                        <a href="@Url.Action("Details", "Character", new { id = character.CharacterId })">
                            <img src="@character.ImageUrl" alt="@character.Name" class="character-image" />
                            <div class="character-info">
                                <p class="character-name">@character.Name</p>
                                <p class="character-role">Role: @character.Role</p>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    }
    else
    {
        <p>No characters available.</p>
    }
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#toggleButton').click(function () {
            var $description = $('#description');
            var isExpanded = $description.hasClass('expanded');

            if (!isExpanded) {
                $description.css('height', $description.prop('scrollHeight') + 'px');
            }

            $description.toggleClass('expanded');

            if (isExpanded) {
                $description.css('height', '100px');
            }

            $(this).text(isExpanded ? 'Read more' : 'Hide');
        });
    });
</script>

<style>
    a {
        text-decoration: none;
    }

    .anime-details {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        background-color: #1c1c1c;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        color: #f0f0f0;
        font-family: 'Arial', sans-serif;
    }

    .anime-header {
        display: flex;
        align-items: flex-start;
        margin-bottom: 20px;
    }

    .anime-image {
        width: 200px;
        height: auto;
        border-radius: 10px;
        margin-right: 20px;
    }

    .anime-info {
        flex-grow: 1;
    }

        .anime-info h1 {
            font-size: 32px;
            margin-bottom: 10px;
            color: #ffa500;
        }

        .anime-info p {
            font-size: 16px;
            line-height: 1.6;
            text-align: justify;
            color: #dcdcdc;
        }

    .description {
        height: 100px;
        overflow: hidden;
        transition: height 1s ease;
    }

        .description.expanded {
            height: auto;
        }

    #toggleButton {
        display: block;
        background-color: #ffa500;
        color: black;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 10px;
    }

    .genres-section,
    .statistics-section,
    .related-anime-section,
    .characters-section,
    .trailer-section {
        margin-top: 20px;
    }

    .trailer-video {
        display: flex;
        justify-content: center;
    }
    .genres-list {
        list-style-type: none;
        padding: 0;
        text-align: center;
    }

    .genre-item {
        display: inline-block;
        margin: 5px;
        background-color: #ffa500;
        color: black;
        padding: 5px 15px;
        border-radius: 15px;
        font-weight: bold;
    }

    .statistics-section p {
        font-size: 16px;
        color: #f0f0f0;
        margin: 5px 0;
    }

    .related-anime-list {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .related-anime-item {
        width: 180px;
        margin: 10px 0;
        padding: 10px;
        background-color: #2c2c2c;
        border-radius: 10px;
        text-align: center;
    }

        .related-anime-item img {
            width: 100%;
            height: auto;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .related-anime-item p {
            font-size: 14px;
            margin-top: 5px;
            
        }

    .characters-list {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .character-item {
        width: 150px;
        margin: 10px 0;
        padding: 10px;
        background-color: #2c2c2c;
        border-radius: 10px;
        text-align: center;
    }

    .character-image {
        width: 100%;
        height: auto;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    .character-info {
        color: #dcdcdc;
    }

    .character-name {
        font-size: 14px;
        margin-top: 10px;
        color: #ffa500;
    }

    .character-role {
        font-size: 12px;
        color: #b0b0b0;
    }

    .media-title {
        font-size: 14px;
        font-weight: bold;
        color: #ffa500;
    }

    .media-type {
        font-size: 12px;
        color: #b0b0b0;
    }
</style>

AnimeLibrary/Views/Anime/Genre.cshtml
@model AnimeLibrary.Models.HomeViewModel

@{
    ViewData["Title"] = "Anime";
}

<h2>@ViewData["Title"]</h2>

<div class="dropdown-content">
    @foreach (var genre in Model.Genres)
    {
        <a asp-controller="Anime" asp-action="Genre" asp-route-genre="@genre">@genre</a>
    }
</div>

    @if (Model.AllAnimes != null && Model.AllAnimes.Any())
    {
        <div class="anime-list">
            @foreach (var anime in Model.AllAnimes)
            {
                <div class="anime-item">
                    <a asp-controller="Anime" asp-action="Details" asp-route-id="@anime.Id">
                    <h3>@anime.EnglishTitle</h3>
                    <img src="@anime.CoverImage" alt="Image">
                    </a>
                </div>
            }
        </div>
    }
</div>


<style>
    
    .dropdown-content {
        position: fixed; /* Фиксированная позиция */
        top: 150px; /* Располагаем список сразу после шапки страницы */
        left: 0; /* Прикрепляем список к левому краю страницы */
        display: block; /* Отображаем по умолчанию */
        background-color: black; /* Цвет фона */
        min-width: 160px; /* Минимальная ширина */
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); /* Тень */
        z-index: 1; /* На переднем плане */
        max-height: 575px; /* Максимальная высота списка для возможности прокрутки */
        overflow-y: auto; /* Включаем вертикальную прокрутку */
    }



        .dropdown-content::-webkit-scrollbar {
            width: 5px; /* Ширина полосы прокрутки */
        }

        .dropdown-content::-webkit-scrollbar-thumb {
            background-color: #888; /* Цвет ползунка */
            border-radius: 10px; /* Скругление углов ползунка */
        }

        .dropdown-content a {
            display: block; /* Сделать ссылки блочными элементами */
            padding: 12px 16px; /* Отступы вокруг текста ссылок */
            color: white; /* Цвет текста ссылок */
            text-decoration: none; /* Убираем подчеркивание текста ссылок */
        }

            .dropdown-content a:hover {
                background-color: #555; /* Цвет фона ссылок при наведении */
            }



    a{
        text-decoration: none;
        color: white;
    }

    a:hover{
        color: #ffa500;
    }
    .content-wrapper {
        display: flex;
        align-items: flex-start;
    }

    .genre-list {
        flex: 1;
        margin-right: 40px; /* Отступ между списком жанров и списком аниме */
        background-color: #ffa500; /* Светлый фон для списка жанров */
        padding: 20px;
        border-radius: 10px; /* Скругленные углы */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Тень для списка жанров */
    }

    .genre-item {
        background-color: black; /* Фон для каждого жанра */
        margin-bottom: 10px;
        padding: 10px;
        border-radius: 10px; /* Скругленные углы для жанров */
        text-align: center;

    }

    .anime-list {
        display: grid;
        grid-template-columns: repeat(5, 1fr);
        gap: 10px;
        flex: 3; /* Занимает оставшееся пространство */
    }

    .anime-item {
        border: 1px solid #ccc;
        padding: 10px;
        text-align: center;
    }

        .anime-item img {
           
            object-fit: cover; /* Обрезка изображения для поддержания пропорций без искажений */
        }
</style>

AnimeLibrary/Views/Anime/_AnimeListPartial.cshtml
@model List<AnimeLibrary.Models.AnimeViewModel>

@foreach (var anime in Model)
{
    <div class="anime-item">
        <a asp-controller="Anime" asp-action="Details" asp-route-id="@anime.Id">
            <h3 class="anime-title">@anime.RomajiTitle</h3>
            <img src="@anime.CoverImage" alt="@anime.RomajiTitle" />
        </a>
    </div>
}

AnimeLibrary/Views/Anime/_SearchResults.cshtml
@model List<AnimeLibrary.Models.AnimeViewModel>

<div class="search-results">
    @if (Model != null && Model.Any())
    {
        @foreach (var anime in Model)
        {
            <a asp-controller="Anime" asp-action="Details" asp-route-id="@anime.Id" class="search-result-item">
                <div class="anime-item">
                    <img src="@anime.CoverImage" alt="@anime.EnglishTitle" class="anime-cover" />
                    <div class="anime-info">
                        <h3 class="anime-title">@anime.EnglishTitle</h3>
                        <p class="anime-description">@anime.Description</p>
                    </div>
                </div>
            </a>
        }
    }
    else
    {
        <p class="no-results">No results found</p>
    }
</div>
<style>
    .search-results {
        display: flex;
        flex-direction: column;
        background-color: #1e1e1e;
        border-radius: 10px;
        padding: 10px;
        max-height: 300px;
        overflow-y: auto;
    }

    .search-result-item {
        display: flex;
        align-items: center;
        padding: 10px;
        border-bottom: 1px solid #333;
        text-decoration: none;
        color: white;
    }

        .search-result-item:hover {
            background-color: #333;
        }

    .anime-item {
        display: flex;
        align-items: center;
    }

    .anime-cover {
        width: 50px;
        height: 75px;
        border-radius: 5px;
        margin-right: 10px;
    }

    .anime-info {
        display: flex;
        flex-direction: column;
    }

    .anime-title {
        font-size: 16px;
        margin: 0;
        color: #ffa500;
    }

    .anime-description {
        font-size: 12px;
        color: #ccc;
        margin: 5px 0 0;
        overflow: hidden;
        text-overflow: ellipsis;
        max-height: 120px;
    }

    .no-results {
        text-align: center;
        color: #ccc;
        padding: 10px;
    }
</style>