AnimeLibrary/Models/MangaViewModel.cs
namespace AnimeLibrary.Models
{
    public class MangaViewModel
    {
        public int Id { get; set; }
        public string? TitleEnglish { get; set; }
        public string? TitleRomaji { get; set; }
        public string? TitleNative { get; set; }
        public string? CoverImage { get; set; }
        public string? Description { get; set; }
        public int? Chapters { get; set; }
        public List<string>? Genres { get; set; }
        public string? Genre { get; set; }
        public int? Volumes { get; set; }
        public double? Score { get; set; }
        public double? AverageScore { get; set; }
        public DateTime? StartDate { get; set; }
        public string MediaType { get; set; }
        public List<Media> Mangas { get; set; }
        public List<MangaViewModel> TrendingManga { get; set; }
        public List<MangaViewModel> PopularManga { get; set; }
        public List<MangaViewModel> PopularManhwa { get; set; }
        public List<RelatedMangaViewModel> RelatedManga { get; set; }
        public List<MangaViewModel> AllMangas { get; set; }
        public class RelatedMangaViewModel
        {
            public int Id { get; set; }
            public string Title { get; set; }
            public string CoverImage { get; set; }
            public string Type { get; set; }
        }
    }
    public class MangaGenreViewModel
    {
        public string Genre { get; set; }
        public List<MangaViewModel> Mangas { get; set; }
        public List<string> Genres { get; set; }
    }

}

AnimeLibrary/Controllers/AnimeController.cs
using AnimeLibrary.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Threading.Tasks;

namespace AnimeLibrary.Controllers
{
    public class AnimeController : Controller
    {
        private readonly AniListService _aniListService;
        private readonly UserManager<ApplicationUser> _userManager;

        public AnimeController(AniListService aniListService, UserManager<ApplicationUser> userManager)
        {
            _aniListService = aniListService;
            _userManager = userManager;
        }
        [ResponseCache(Duration = 60)]
        public async Task<IActionResult> Details(int id)
        {
            var anime = await _aniListService.GetAnimeDetails(id);
            if (anime == null)
            {
                return NotFound();
            }
            var relatedAnime = await _aniListService.GetRelatedAnimeAsync(id);
            var viewModel = new AnimeViewModel
            {
                Id = anime.Id,
                RomajiTitle = anime.RomajiTitle,
                EnglishTitle = anime.EnglishTitle,
                NativeTitle = anime.NativeTitle,
                CoverImage = anime.CoverImage,
                Description = anime.Description,
                Genres = anime.Genres,
                Score = anime.Score,
                StartDate = anime.StartDate,
                Episodes = anime.Episodes,
                RelatedAnime = relatedAnime,
                Characters = anime.Characters,
                Trailer = anime.Trailer,
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Genre(string genre, int page = 1, int perPage = 15)
        {
            // Асинхронно получаем список аниме по жанру и странице
            var animeListByGenre = await _aniListService.ListAnimeGenre(genre, page, perPage);
            if (animeListByGenre == null || !animeListByGenre.Any())
            {
                return NotFound();
            }

            // Преобразуем список Media в список AnimeViewModel
            var animeViewModels = animeListByGenre.Select(media => new AnimeViewModel
            {
                Id = media.Id,
                RomajiTitle = media.Title.Romaji,
                EnglishTitle = media.Title.English,
                NativeTitle = media.Title.Native,
                CoverImage = media.CoverImage.Large,
                Description = media.Description,
                Genres = media.Genres,
                Genre = genre,
                Score = media.Score,
                Episodes = media.Episodes,
                AverageScore = media.AverageScore,
            }).ToList();

            var allGenres = await _aniListService.GetGenresAsync();

            var viewModel = new AnimeGenreViewModel
            {
                Genre = genre,
                Animes = animeViewModels,
                Genres = allGenres ?? new List<string>()
            };

            return View("Genre", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToViewed(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var anime = await _aniListService.GetAnimeDetails(id);
            if (anime == null)
            {
                return NotFound();
            }

            if (user.ViewedAnimes == null)
            {
                user.ViewedAnimes = new List<int>();
            }

            if (!user.ViewedAnimes.Contains(anime.Id))
            {
                user.ViewedAnimes.Add(anime.Id);
                await _userManager.UpdateAsync(user);
            }

            return RedirectToAction("ViewedContent", "Account");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveFromViewed(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (user.ViewedAnimes == null || !user.ViewedAnimes.Contains(id))
            {
                return NotFound();
            }

            user.ViewedAnimes.Remove(id);
            await _userManager.UpdateAsync(user);

            return RedirectToAction("ViewedContent", "Account");
        }

        public async Task<IActionResult> Search(string title)
        {
            if (string.IsNullOrWhiteSpace(title))
            {
                return PartialView("_SearchResults", new List<AnimeViewModel>());
            }

            try
            {
                var searchResults = await _aniListService.SearchAnimeByTitleAsync(title);
                var animeList = searchResults["Page"]["media"].ToObject<List<Media>>();

                var animeViewModels = animeList.Select(media => new AnimeViewModel
                {
                    Id = media.Id,
                    RomajiTitle = media.Title?.Romaji,
                    EnglishTitle = media.Title?.English,
                    NativeTitle = media.Title?.Native,
                    CoverImage = media.CoverImage?.Large,
                    Description = media.Description,
                    Genres = media.Genres,
                    Score = media.Score.HasValue ? media.Score.Value / 10.0 : (double?)null,
                    Episodes = media.Episodes,
                    AverageScore = media.AverageScore,
                }).ToList();

                return PartialView("_SearchResults", animeViewModels);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return PartialView("_SearchResults", new List<AnimeViewModel>());
            }
        }

        public async Task<IActionResult> LoadMoreAnime(string genre, int page = 1, int perPage = 15)
        {
            var animeListByGenre = await _aniListService.ListAnimeGenre(genre, page, perPage);
            if (animeListByGenre == null || !animeListByGenre.Any())
            {
                return NotFound();
            }

            var animeViewModels = animeListByGenre.Select(media => new AnimeViewModel
            {
                Id = media.Id,
                RomajiTitle = media.Title.Romaji,
                EnglishTitle = media.Title.English,
                NativeTitle = media.Title.Native,
                CoverImage = media.CoverImage.Large,
                Description = media.Description,
                Genres = media.Genres,
                Genre = genre,
                Score = media.Score,
                Episodes = media.Episodes,
                AverageScore = media.AverageScore,
            }).ToList();

            return PartialView("_AnimeListPartial", animeViewModels);
        }




    }

}

AnimeLibrary/Controllers/MangaController.cs
using AnimeLibrary.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using static AnimeLibrary.Models.TestModel;

public class MangaController : Controller
{
    private readonly AniListService _aniListService;
    private readonly UserManager<ApplicationUser> _userManager;


    public MangaController(AniListService aniListService, UserManager<ApplicationUser> userManager)
    {
        _aniListService = aniListService;
        _userManager = userManager;
    }
    [ResponseCache(Duration = 60)]
    public async Task<IActionResult> Index()
    {
        var trendingManga = await _aniListService.GetTrendingMangaAsync();
        var popularManga = await _aniListService.GetPopularMangaAsync();
        var popularManhwa = await _aniListService.GetPopularManhwaAsync();
        var genres = await _aniListService.GetGenresAsync();
        var viewModel = new MangaViewModel
        {
            TrendingManga = trendingManga ?? new List<MangaViewModel>(),
            PopularManga = popularManga ?? new List<MangaViewModel>(),
            PopularManhwa = popularManhwa ?? new List<MangaViewModel>(),
            Genres = genres
            
        };

        return View(viewModel);
    }
    public async Task<IActionResult> Details(int id)
    {
        // Асинхронно получаем данные об аниме
        var manga = await _aniListService.GetMangaDetails(id);
        if (manga == null)
        {
            return NotFound();
        }
        var relatedManga = await _aniListService.GetRelatedMangaAsync(id);
        var viewModel = new MangaViewModel
        {
            Id = manga.Id,
            TitleRomaji = manga.TitleRomaji,
            TitleEnglish = manga.TitleEnglish,
            TitleNative = manga.TitleNative,
            Description = manga.Description,
            Chapters = manga.Chapters,
            Volumes = manga.Volumes,
            Score = manga.Score,
            CoverImage = manga.CoverImage,
            StartDate = manga.StartDate,
            Genres = manga.Genres,
            RelatedManga = relatedManga
        };

        return View(viewModel);
    }
    public async Task<IActionResult> Genre(string genre, int page = 1, int perPage = 15)
    {
        // Асинхронно получаем список манги по жанру
        var mangaListByGenre = await _aniListService.ListMangaGenre(genre, page, perPage);
        if (mangaListByGenre == null || !mangaListByGenre.Any())
        {
            return NotFound();
        }

        var mangaViewModels = mangaListByGenre.Select(media => new MangaViewModel
        {
            Id = media.Id,
            TitleRomaji = media.Title.Romaji,
            TitleEnglish = media.Title.English,
            TitleNative = media.Title.Native,
            CoverImage = media.CoverImage.Large,
            Description = media.Description,
            Genres = media.Genres,
            Score = media.Score,
            Genre = genre,
            Chapters = media.Chapters,
            AverageScore = media.AverageScore
        }).ToList();

        var allGenres = await _aniListService.GetGenresAsync();

        var viewModel = new MangaGenreViewModel
        {
            Genre = genre,
            Mangas = mangaViewModels,
            Genres = allGenres ?? new List<string>()
        };

        return View("Genre", viewModel);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddToViewed(int id)
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return RedirectToAction("Login", "Account");
        }

        var manga = await _aniListService.GetMangaDetails(id);
        if (manga == null)
        {
            return NotFound();
        }

        if (user.ViewedMangas == null)
        {
            user.ViewedMangas = new List<int>();
        }

        if (!user.ViewedMangas.Contains(manga.Id))
        {
            user.ViewedMangas.Add(manga.Id);
            await _userManager.UpdateAsync(user);
        }

        return RedirectToAction("ViewedContent", "Account");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RemoveFromViewed(int id)
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return RedirectToAction("Login", "Account");
        }

        if (user.ViewedMangas == null || !user.ViewedMangas.Contains(id))
        {
            return NotFound();
        }

        user.ViewedMangas.Remove(id);
        await _userManager.UpdateAsync(user);

        return RedirectToAction("ViewedContent", "Account");
    }
    public async Task<IActionResult> Search(string title)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            return PartialView("_SearchResults", new List<MangaViewModel>());
        }

        try
        {
            var searchResults = await _aniListService.SearchMangaByTitleAsync(title);
            var mangaList = searchResults["Page"]["media"].ToObject<List<Media>>();

            var mangaViewModels = mangaList.Select(media => new MangaViewModel
            {
                Id = media.Id,
                TitleRomaji = media.Title?.Romaji,
                TitleEnglish = media.Title?.English,
                TitleNative = media.Title?.Native,
                CoverImage = media.CoverImage?.Large,
                Description = media.Description,
                Genres = media.Genres,
                Score = media.Score.HasValue ? media.Score.Value / 10.0 : (double?)null,
                AverageScore = media.AverageScore,
            }).ToList();

            return PartialView("_SearchResults", mangaViewModels);
        }
        catch (Exception ex)
        {
            ViewBag.ErrorMessage = ex.Message;
            return PartialView("_SearchResults", new List<MangaViewModel>());
        }
    }
    public async Task<IActionResult> LoadMoreManga(string genre, int page = 1, int perPage = 15)
    {
        // Асинхронно получаем список аниме по жанру и странице
        var mangaListByGenre = await _aniListService.ListMangaGenre(genre, page, perPage);
        if (mangaListByGenre == null || !mangaListByGenre.Any())
        {
            return NotFound();
        }

        var mangaViewModels = mangaListByGenre.Select(media => new MangaViewModel
        {
            Id = media.Id,
            TitleRomaji = media.Title.Romaji,
            TitleEnglish = media.Title.English,
            TitleNative = media.Title.Native,
            CoverImage = media.CoverImage.Large,
            Description = media.Description,
            Genres = media.Genres,
            Genre = genre,
            Score = media.Score,
            Chapters = media.Chapters,
            AverageScore = media.AverageScore,
        }).ToList();

        return PartialView("_MangaListPartial", mangaViewModels);
    }

}

AnimeLibrary/Views/Shared/Components/News/NewsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

public class NewsViewComponent : ViewComponent
{
    private readonly ApplicationDbContext _context;

    public NewsViewComponent(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var news = await _context.News
            .OrderByDescending(n => n.CreatedAt)
            .Take(5)
            .ToListAsync();
        return View(news);
    }
}

AnimeLibrary/Views/Manga/Details.cshtml
@model AnimeLibrary.Models.MangaViewModel

@{
    ViewData["Title"] = Model.TitleRomaji;
}

<div class="manga-details">
    <div class="manga-header">
        <img src="@Model.CoverImage" alt="@Model.TitleEnglish" class="manga-image" />
        <div class="manga-info">
            <h1>@Model.TitleRomaji</h1>
            <h5>@Model.TitleEnglish</h5>
            <h5>@Model.TitleNative</h5>
            <div id="description" class="description">
                <p>@Html.Raw(Model.Description)</p>
            </div>
            <button id="toggleButton">Подробнее</button>
        </div>
    </div>

    @if (Model.Genres != null && Model.Genres.Any())
    {
        <div class="genres-section">
            <h3>Жанры</h3>
            <ul class="genres-list">
                @foreach (var genre in Model.Genres)
                {
                    <li class="genre-item">@genre</li>
                }
            </ul>
        </div>
    }
    <form asp-action="AddToViewed" method="post">
        <input type="hidden" name="id" value="@Model.Id" />
        <button type="submit" class="btn btn-primary">Добавить в просмотренное</button>
    </form>
    <div class="statistics-section">
        <h3>Статистика</h3>
        <p>Оценка: @(Model.Score.HasValue ? Model.Score.Value.ToString("0.0") : "Rating is unknown.")</p>
        <p>Главы: @(Model.Chapters.HasValue ? Model.Chapters.Value.ToString() : "100+")</p>
        <p>Дата выхода: @(Model.StartDate.HasValue ? Model.StartDate.Value.ToString("dd.MM.yyyy") : "Release date is unknown.")</p>
    </div>

    @if (Model.RelatedManga != null && Model.RelatedManga.Any())
    {
        <div class="related-manga-section">
            <h3>Связанное</h3>
            <div class="related-manga-list">
                @foreach (var related in Model.RelatedManga)
                {
                    <div class="related-manga-item">
                        @if (@related.Type == "ANIME")
                        {
                            <a class="related-link" href="@Url.Action("Details", "Anime", new { id = related.Id })">
                                <img src="@related.CoverImage" alt="Image @related.Title" />
                                <p class="media-title">@related.Title</p>
                                <p class="media-type">@related.Type</p>
                            </a>
                        }
                        else
                        {
                            <a class="related-link" href="@Url.Action("Details", "Manga", new { id = related.Id })">
                                <img src="@related.CoverImage" alt="Image @related.Title" />
                                <p class="media-title">@related.Title</p>
                                <p class="media-type">@related.Type</p>
                            </a>
                        }
                    </div>
                }
            </div>
        </div>
    }
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#toggleButton').click(function () {
            var $description = $('#description');
            var isExpanded = $description.hasClass('expanded');

            if (!isExpanded) {
                $description.css('height', $description.prop('scrollHeight') + 'px');
            }

            $description.toggleClass('expanded');

            if (isExpanded) {
                $description.css('height', '100px');
            }

            $(this).text(isExpanded ? 'Read more' : 'Hide');
        });
    });
</script>

<style>
    a {
        text-decoration: none;
    }

    .manga-details {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        background-color: #1c1c1c;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        color: #f0f0f0;
        font-family: 'Arial', sans-serif;
    }

    .manga-header {
        display: flex;
        align-items: flex-start;
        margin-bottom: 20px;
    }

    .manga-image {
        width: 200px;
        height: auto;
        border-radius: 10px;
        margin-right: 20px;
    }

    .manga-info {
        flex-grow: 1;
    }

        .manga-info h1 {
            font-size: 32px;
            margin-bottom: 10px;
            color: #ffa500;
        }

        .manga-info p {
            font-size: 16px;
            line-height: 1.6;
            text-align: justify;
            color: #dcdcdc;
        }

    .description {
        height: 100px;
        overflow: hidden;
        transition: height 1s ease;
    }

        .description.expanded {
            height: auto;
        }

    #toggleButton {
        display: block;
        background-color: #ffa500;
        color: black;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 10px;
    }

    .genres-section,
    .statistics-section,
    .related-manga-section {
        margin-top: 20px;
    }

    .genres-list {
        list-style-type: none;
        padding: 0;
        text-align: center;
    }

    .genre-item {
        display: inline-block;
        margin: 5px;
        background-color: #ffa500;
        color: black;
        padding: 5px 15px;
        border-radius: 15px;
        font-weight: bold;
    }

    .statistics-section p {
        font-size: 16px;
        color: #f0f0f0;
        margin: 5px 0;
    }

    .related-manga-list {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .related-manga-item {
        width: 180px;
        margin: 10px 0;
        padding: 10px;
        background-color: #2c2c2c;
        border-radius: 10px;
        text-align: center;
    }

        .related-manga-item img {
            width: 100%;
            height: auto;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .related-manga-item p {
            font-size: 14px;
            margin-top: 5px;
            
        }

    .media-title {
        font-size: 14px;
        font-weight: bold;
        color: #ffa500;
    }

    .media-type {
        font-size: 12px;
        color: #b0b0b0;
    }
</style>

AnimeLibrary/Views/Manga/Index.cshtml
@model AnimeLibrary.Models.MangaViewModel

@{
    ViewData["Title"] = "Main Page";
}

<form id="searchForm" asp-controller="Manga" asp-action="Search" method="get">
    <input type="text" id="searchInput" name="title" placeholder="Search Manga..." autocomplete="off" />
    <div id="searchResults" class="dropdown-content-search"></div>
</form>



<h2 class="category">Сейчас в тренде</h2>
<div class="anime-list">
    @foreach (var manga in Model.TrendingManga)
    {
        <div class="anime-item">
            <a asp-controller="Manga" asp-action="Details" asp-route-id="@manga.Id">
                <img src="@manga.CoverImage" alt="@manga.TitleRomaji" />
                <h3 class="anime-title">@manga.TitleRomaji</h3>
                
            </a>
        </div>
    }
</div>

<h2 class="category">Популярное</h2>
<div class="anime-list">
    @foreach (var manga in Model.PopularManga)
    {
        <div class="anime-item">
            <a asp-controller="Manga" asp-action="Details" asp-route-id="@manga.Id">
                <img src="@manga.CoverImage" alt="@manga.TitleRomaji" />
                <h3 class="anime-title">@manga.TitleRomaji</h3>
                
            </a>
        </div>
    }
</div>
<h3>Новости</h3>

@await Component.InvokeAsync("News")
<a asp-controller="News" asp-action="Index" class="btn btn-primary">Все новости</a>

<div class="dropdown-content">
    @foreach (var genre in Model.Genres)
    {
        if (genre != "Hentai")
        {
            <a asp-controller="Manga" asp-action="Genre" asp-route-genre="@genre">@genre</a>
        }
        
    }
</div>
<div class="dropdown">
    <button class="dropdown-btn">☰ Menu</button>
    <div class="dropdown-content">
    </div>
</div>


<style>
    .dropdown-content {
        display: block; 
        position: fixed;
        top: 100px;
        left: 0;
        background-color: black;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        max-height: 575px;
        overflow-y: auto;
    }

        .dropdown-content::-webkit-scrollbar {
            width: 5px;
        }

        .dropdown-content::-webkit-scrollbar-thumb {
            background-color: #888;
            border-radius: 10px; 
        }

        .dropdown-content a {
            display: block;
            padding: 12px 16px;
            color: white;
            text-decoration: none;
        }

            .dropdown-content a:hover {
                background-color: #555;
            }

    .dropdown-btn {
        display: none;
        background-color: black;
        color: white;
        padding: 10px 15px;
        border: none;
        cursor: pointer;
        font-size: 16px;
        position: fixed;
        top: 10px;
        right: 10px;
        z-index: 2;
    }

        .dropdown-btn:hover {
            background-color: #555;
        }

    /* Медиазапросы для мобильных устройств */
    @@media (max-width: 768px) {
        .dropdown-btn {
            display: block; 
            top: 100px;
        }

            .dropdown-btn.active + .dropdown-content {
                display: block;
            }
    }

    .anime-list {
        display: flex;
        overflow-x: auto; 
        overflow-y: hidden;
        padding: 10px;
        max-height: 340px;
    }

        .anime-list::-webkit-scrollbar {
            height: 10px;
        }

        .anime-list::-webkit-scrollbar-track {
            background: transparent;
            border-radius: 20px;
        }

        .anime-list::-webkit-scrollbar-thumb {
            background: #ffa500;
            border-radius: 20px;
        }

            .anime-list::-webkit-scrollbar-thumb:hover {
                background: #ff8c00;
            }

    .anime-list {
        scrollbar-width: thin;
        scrollbar-color: #ffa500 transparent;
    }

    .anime-list {
        -ms-overflow-style: -ms-autohiding-scrollbar;
    }

    .category {
        font-family: 'B612', sans-serif;
        font-style: italic;
        font-weight: 700;
    }

    .anime-item {
        flex: 0 0 auto;
        margin: 0 10px;
        text-align: center;
        max-width: 150px;
        word-wrap: break-word;
        transition: transform 0.3s ease;
    }

        .anime-item:hover {
            transform: scale(1.1);
        }

        .anime-item img {
            width: 150px;
            height: 225px;
            object-fit: cover;
        }

    .anime-title {
        font-family: 'B612', sans-serif;
        font-style: italic;
        font-weight: 700;
        font-size: 15px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: normal;
        max-height: 60px;
        line-height: 20px;
    }

    .anime-details ul li {
        display: inline-block;
        margin-right: 10px;
        background-color: #e0e0e0;
        padding: 5px 10px;
        border-radius: 15px;
        font-size: 14px;
        color: #333;
    }

    a {
        text-decoration: none;
    }

    a {
        color: white;
    }
        a:hover {
            color: #ffa500;
        }

    @@media (max-width: 768px) {
        .anime-list {
            max-height: none;
        }

        .anime-item {
            margin-bottom: 20px;
            max-width: 20%;
        }

            .anime-item img {
                width: 100%;
                height: auto;
            }
    }

    .dropdown-content-search {
        position: absolute;
        top: 100px;
        left: 0;
        width: 20%;
        background-color: black;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 999;
        max-height: 300px;
        overflow-y: auto;
        display: none;
    }

        .dropdown-content-search a {
            display: block;
            padding: 12px 16px;
            color: white;
            text-decoration: none;
        }

            .dropdown-content-search a:hover {
                background-color: #555;
            }

    @@media (max-width: 480px) {
        .dropdown-content {
            display: none;
            min-width: 100px;
            top: 100px;
        }

        .anime-title {
            font-size: 12px;
        }

        .anime-details ul li {
            font-size: 12px;
            padding: 3px 7px;
        }
    }
    @@media (max-width: 1000px){
        .dropdown-content{
            display: none;
        }
    }
</style>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        var dropdownBtn = document.querySelector('.dropdown-btn');
        dropdownBtn.addEventListener('click', function () {
            this.classList.toggle('active');
            var dropdownContent = document.querySelector('.dropdown-content');
            if (this.classList.contains('active')) {
                dropdownContent.style.display = 'block';
            } else {
                dropdownContent.style.display = 'none';
            }
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('#searchInput').on('input', function () {
            var query = $(this).val();
            if (query.length > 2) { 
                $.ajax({
                    url: '@Url.Action("Search", "Manga")',
                    type: 'GET',
                    data: { title: query },
                    success: function (data) {
                        $('#searchResults').html(data).show();
                    },
                    error: function () {
                        $('#searchResults').hide();
                    }
                });
            } else {
                $('#searchResults').hide();
            }
        });

        $(document).click(function (e) {
            if (!$(e.target).closest('#searchForm').length) {
                $('#searchResults').hide();
            }
        });
    });
</script>

AnimeLibrary/Views/Manga/_MangaListPartial.cshtml
@model List<AnimeLibrary.Models.MangaViewModel>

@foreach (var manga in Model)
{
    <div class="anime-item">
        <a asp-controller="Manga" asp-action="Details" asp-route-id="@manga.Id">
            <h3 class="anime-title">@manga.TitleRomaji</h3>
            <img src="@manga.CoverImage" alt="@manga.TitleRomaji" />
        </a>
    </div>
}